name: Update Queensland Data
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download CSV
        run: |
          # Încercăm descărcarea. Dacă serverul dă eroare, scriptul se oprește aici.
          curl -fL "https://www.data.qld.gov.au/dataset/8aa66eca-4b37-4864-920a-02d08fd2fba3/resource/a512e9a8-c374-4416-a77d-1be85f3c796e/download/water-licence-attributes.csv" -o water-licence-attributes.csv

      - name: Save to GitHub
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add water-licence-attributes.csv
          # Trimitem pe GitHub doar dacă fișierul are conținut (mai mare de 100 bytes)
          if [ $(stat -c%s "water-licence-attributes.csv") -gt 100 ]; then
            git commit -m "Update date live" && git push
          else
            echo "Fișierul descărcat este gol sau prea mic, ignorăm update-ul."
          fi
