name: Depozit Automat Date
on:
  schedule:
    - cron: '0 0 * * *' # Rulează automat în fiecare noapte
  workflow_dispatch:      # Buton pentru rulare manuală

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Descarcă fișierul complet (cu reîncercare)
        run: |
          # Încearcă să descarce de 3 ori dacă serverul dă eroare
          curl --retry 3 --retry-delay 60 -L "https://www.data.qld.gov.au/dataset/8aa66eca-4b37-4864-920a-02d08fd2fba3/resource/a512e9a8-c374-4416-a77d-1be85f3c796e/download/water-licence-attributes.csv" -o data_temp.csv

      - name: Verifică dacă datele sunt valide
        run: |
          # Verificăm dacă fișierul are peste 10MB. Dacă e mai mic, înseamnă că e eroare.
          SIZE=$(stat -c%s "data_temp.csv")
          if [ $SIZE -lt 10000000 ]; then
            echo "Eroare: Fișierul descărcat este prea mic ($SIZE bytes). Păstrăm versiunea veche."
            exit 1
          fi
          mv data_temp.csv water-licence-attributes.csv

      - name: Salvează în GitHub
        run: |
          git config --global user.name "Data Bot"
          git config --global user.email "bot@github.com"
          git add water-licence-attributes.csv
          git commit -m "Update automat: $(date +'%Y-%m-%d')" || exit 0
          git push
